sudo: false
language: python
matrix:
  include:
    - python: "3.5"
      env: LTD_MASON_BUILD=true
install:
  - pip install -r requirements.txt
  - pip install "ltd-mason>=0.2,<0.3"
script:
  - sphinx-build -b html -a -n -d _build/doctree . _build/html
after_success:
  - ltd-mason-travis --html-dir _build/html
env:
  global:
    - LTD_MASON_BUILD=false  # disable builds in regular text matrix
    - LTD_MASON_PRODUCT="smtn-008"
    # Add AWS and LTD Keeper credentials as encrypted secrets here
    - secure: "YJ+xNGBmLATC18o4J38QTDXIPXFd2bbgIyMfllY5Kqoq+jzj9OAgwJgyiTV/FpxAvzeg46Py4J31ckKDrIY26JUp14mE60ea1BsH8myX8A8wD+QNDl91BMdEuauDbkqCOdoEmJf6uVmDIfFnH4F6R6pcvELzXWxBjo6YujzMklyJtzBytZTIZz9yxN//rDKG+HXjR7pzWYTdD0Vn5j+t3GevrHCORzNz0639cwnj/vsvF7O0NycGtEnj9zPaPvg1n4CQugrN0I0y1SOeOom99ApEO+TrK1KAPh5kmIjzCAv6hMmfrkCioZQud+DZlyi1HR9cH4kK23D/YyYeb1PY9ajq/9LuurNnWhG9/7BrM+crQsQ19qCDcgdp9f08Ur1w51HRmr2fmR5Z8qZlFbnIu6nt7rK7TM8W6uPm8Wg+9Wnhh7HDD8cxfwCoIzgxEimNtF+AHgNGNhWKrL4rV2g8GcgxXbAi2q2FqmaL79u4uFZm93wgvWiE22Kb50SAsvLgxOiFKRcpqm22CDvhM0XQULA7ntGZhShG3FJ6p1S6iNr2wp7ePH/BQpPTveQW3T5p9g5Vhf4Dc5VmUanMD9dcVF4ELE9oomaVOeja1HLW9OL1ZAZd6xV91r3bUwRPV1FyJ26MqMgGHthK+YR5VoIiTnQG7ySeZ5rJTLjN17LKkiI="
    - secure: "AmhkUX3GXe79Q/U8blyQRP8lOgvCt3RHiiR6bwdDAn4K6MSobSrPK+hBvYRpKYdNy79D28Hmuwip6/w2TJFTSl04R5F+beTBLmFY1yqkSCKqY5BnAsyoj4PgReLGwCZQ6trFl6FslX6LdFa57lZdSFoiLFLNDysFVj5LRObhLIkdwzzcQVORdT5lvbHSypQKtvtjQHXtEkpJMv9f4B2Y+hp8dNk+uo/8dSEw+/c4Ml2QZSOZ2PLRGbWLONF106Pf5ZtkVyBtckVy1SqqrezlloqHZaVu6IKf1IaijaoW8u7QXb3MpHJE9g1KwUbxQ5qBrmIVEHoxbGP7yDAmX10eIXfZyBfUwbuMI7JjYgs4K4HhoU7qQO6xPukHtcQN8j7bSmw+ha5oTh0aYApZhmMthGYCRtPLoBB20F2zo9MytTavaMnoYchpJOM7bfx74n1SdsZ/Qgqvlh/2v3U075Zo0SDeifDBpfkiwkyl/pyV3IgndFg+Z3MMqekdWdX3DuZakUF7wkER/qF3yDui4w1j10lWrI5qYY9qy2PD1YjfDsZRqoNWntDxmF3Le3iPCTk1C9MYAvLUsHpmaWgRompjwYcfY9pEGBe/TCjWg4IAp9gFmbLUZvRhJs95G6YMPW2k/xPRlIEQ8GAi8cabQBBO5rtxLvi1SuDjzg101L21MCc="
